// Emits prisma/schema.<provider>.prisma by prepending the correct datasource/generator
// blocks to the shared prisma/model.prisma fragment. Prisma has no environment variable
// for `datasource.provider`, so this is generated rather than configured (SRS §6.3, P0 task 7).
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

interface ProviderDef {
  outputFile: string;
  datasourceProvider: 'sqlite' | 'postgresql';
  clientOutput: string;
  extraGeneratorLines?: string[];
  note?: string;
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const modelPath = path.join(root, 'prisma', 'model.prisma');
const model = readFileSync(modelPath, 'utf8').trim();

const providers: ProviderDef[] = [
  {
    outputFile: 'schema.sqlite.prisma',
    datasourceProvider: 'sqlite',
    clientOutput: '../packages/db/generated/sqlite',
  },
  {
    outputFile: 'schema.postgres.prisma',
    datasourceProvider: 'postgresql',
    clientOutput: '../packages/db/generated/postgres',
  },
  {
    outputFile: 'schema.d1.prisma',
    datasourceProvider: 'sqlite',
    clientOutput: '../packages/db/generated/d1',
    extraGeneratorLines: ['  previewFeatures = ["driverAdapters"]'],
    note: '// D1 is reached through a Workers binding, not this url — see documents/planning/adr-001-data-access.md.',
  },
];

for (const def of providers) {
  const generatorLines = [
    'generator client {',
    '  provider = "prisma-client-js"',
    `  output   = "${def.clientOutput}"`,
    ...(def.extraGeneratorLines ?? []),
    '}',
  ];
  const datasourceLines = [
    ...(def.note ? [def.note] : []),
    'datasource db {',
    `  provider = "${def.datasourceProvider}"`,
    '  url      = env("DATABASE_URL")',
    '}',
  ];

  const header = [
    '// AUTO-GENERATED by scripts/generate-schemas.ts — do not edit by hand.',
    '// Edit prisma/model.prisma instead and re-run `npm run db:generate-schemas`.',
    '',
    ...generatorLines,
    '',
    ...datasourceLines,
    '',
  ].join('\n');

  const outputPath = path.join(root, 'prisma', def.outputFile);
  writeFileSync(outputPath, `${header}\n${model}\n`, 'utf8');
  console.log(`Generated ${path.relative(root, outputPath)}`);
}
