// Emits prisma/schema.<provider>.prisma by prepending the correct datasource/generator
// blocks to the shared prisma/model.prisma fragment. Prisma has no environment variable
// for `datasource.provider`, so this is generated rather than configured (SRS §6.3, P0 task 7).
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

interface ProviderDef {
  // Each provider gets its own subdirectory (not just its own filename) so `prisma migrate dev`
  // resolves a separate `migrations/` history per provider — sqlite and postgresql migration SQL
  // dialects diverge, so they cannot share one migrations folder (P1 correction to P0's layout,
  // which only had a single-entity placeholder model and hadn't hit this yet).
  dir: string;
  datasourceProvider: 'sqlite' | 'postgresql';
  clientOutput: string;
  extraGeneratorLines?: string[];
  note?: string;
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const modelPath = path.join(root, 'prisma', 'model.prisma');
const model = readFileSync(modelPath, 'utf8').trim();

const providers: ProviderDef[] = [
  {
    dir: 'sqlite',
    datasourceProvider: 'sqlite',
    clientOutput: '../../packages/db/generated/sqlite',
  },
  {
    dir: 'postgres',
    datasourceProvider: 'postgresql',
    clientOutput: '../../packages/db/generated/postgres',
  },
  {
    dir: 'd1',
    datasourceProvider: 'sqlite',
    clientOutput: '../../packages/db/generated/d1',
    note: '// D1 is reached through a Workers binding, not this url — see documents/planning/adr-001-data-access.md.',
  },
];

for (const def of providers) {
  const generatorLines = [
    'generator client {',
    '  provider = "prisma-client-js"',
    `  output   = "${def.clientOutput}"`,
    ...(def.extraGeneratorLines ?? []),
    '}',
  ];
  const datasourceLines = [
    ...(def.note ? [def.note] : []),
    'datasource db {',
    `  provider = "${def.datasourceProvider}"`,
    '  url      = env("DATABASE_URL")',
    '}',
  ];

  const header = [
    '// AUTO-GENERATED by scripts/generate-schemas.ts — do not edit by hand.',
    '// Edit prisma/model.prisma instead and re-run `npm run db:generate-schemas`.',
    '',
    ...generatorLines,
    '',
    ...datasourceLines,
    '',
  ].join('\n');

  const outputDir = path.join(root, 'prisma', def.dir);
  mkdirSync(outputDir, { recursive: true });
  const outputPath = path.join(outputDir, 'schema.prisma');
  writeFileSync(outputPath, `${header}\n${model}\n`, 'utf8');
  console.log(`Generated ${path.relative(root, outputPath)}`);
}
